-- Reference data only. Safe in any environment.
--
-- This is NOT a plant-name catalogue. It is a small starting set of entries whose
-- botanical names are well established, added so the identification flow has
-- something to resolve against. Every future row is a human decision - names are
-- never bulk-generated by a model.
--
-- Mock requests, users and responses live in seeds/dev_mock.sql, which refuses to
-- run unless it is explicitly allowed.

insert into public.plants (scientific_name) values
  ('Curcuma longa'),
  ('Zingiber officinale'),
  ('Cannabis sativa'),
  ('Withania somnifera'),
  ('Mentha x piperita')
on conflict (scientific_name) do nothing;

insert into public.plant_aliases (plant_id, alias, language, alias_kind)
select p.id, v.alias, v.language, v.alias_kind
from (values
  ('Curcuma longa',       'כורכום',              'he', 'common'),
  ('Curcuma longa',       'turmeric',            'en', 'common'),
  ('Curcuma longa',       'Curcuma longa',       'la', 'scientific'),
  ('Zingiber officinale', 'ג׳ינג׳ר',             'he', 'common'),
  ('Zingiber officinale', 'זנגביל',              'he', 'common'),
  ('Zingiber officinale', 'ginger',              'en', 'common'),
  ('Zingiber officinale', 'Zingiber officinale', 'la', 'scientific'),
  ('Cannabis sativa',     'קנאביס',              'he', 'common'),
  ('Cannabis sativa',     'cannabis',            'en', 'common'),
  ('Cannabis sativa',     'Cannabis sativa',     'la', 'scientific'),
  ('Withania somnifera',  'אשווגנדה',            'he', 'common'),
  ('Withania somnifera',  'ashwagandha',         'en', 'common'),
  ('Withania somnifera',  'Withania somnifera',  'la', 'scientific'),
  ('Mentha x piperita',   'נענע',                'he', 'common'),
  ('Mentha x piperita',   'peppermint',          'en', 'common'),
  ('Mentha x piperita',   'Mentha x piperita',   'la', 'scientific')
) as v (scientific_name, alias, language, alias_kind)
join public.plants p on p.scientific_name = v.scientific_name
on conflict (plant_id, alias, language) do nothing;
